language: android
android:
  components:
    - tools
    - platform-tools
    - android-16
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - addon-google_apis-google-16
    - sys-img-armeabi-v7a-android-16
